name: obcsapi-go
version: v4.0.5
description: by kkbt
host: 0.0.0.0
port: 8900
token_path: ./token/
token1_live_time: 72h

# å‰ç«¯ååœ°å€ é‚®ä»¶ä¸­ç™»å½•é“¾æ¥ä¼šç”¨åˆ°
front_url: https://kkbt.gitee.io/obweb/#/Memos
backend_url: api.ftls.xyz
wechat_return_str: "ğŸ“© å·²ä¿å­˜ï¼Œ<a href='https://note.ftls.xyz/#/ZK/202209050658'>ç‚¹å‡»æŸ¥çœ‹ä»Šæ—¥ç¬”è®°</a>"

# Obsidian æ–‡ä»¶å¤¹è®¾ç½®

ob_daily_dir: æ—¥å¿—/
ob_daily_attachment_dir: æ—¥å¿—/é™„ä»¶/
ob_daily_other_dir: æ”¯æŒç±»æ–‡ä»¶/

# S3 -> 1 ; CouchDb -> 2
data_source: 2

# CouchDb é…ç½®
couchdb_url: http://admin:password@localhost:5984/
couchdb_db_name: note

# S3 é…ç½®
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# wechat æµ‹è¯•å·/å…¬ä¼—å·
wechat_token: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„Token
wechat_appid: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„AppID
wechat_secret: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID

# smtp é‚®ç®±æœåŠ¡
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@mail.ftls.xyz
  password: xxxxxxxxxxxxxx
  # ä»¥ä¸‹ä¸€ä¸ªæ˜¯å‘é€è€… ä¸€ä¸ªæ˜¯æ¥å—è€…
  mail_sender_address: no-reply@mail.ftls.xyz
  mail_sender_name: "ObCSAPI"
  mail_send_to: yourmail@foxmail.com