name: obcsapi-go # 项目名称
version: v4.2.0 # 项目版本
description: by kkbt # 描述
host: 0.0.0.0 
port: 8900
# 如果部署在二级目录，需求填写这个，否则 Swagger 错误，不使用无需关注
# base_path: /obcsapi

# 前端登录账户密码 有效时间 720h
user: kkbt 
password: password

# Swagger 调试
swagger: true
# debug 模式
debug: false

# 前端后地址 邮件中登录链接会用到
backend_url: api.ftls.xyz
backend_url_full: http://localhost:8900

# S3 -> 1 ; CouchDb -> 2 ; Local -> 3 ; WebDav -> 4
data_source: 3

# CouchDb 配置
couchdb_url: http://admin:password@localhost:5984/
couchdb_db_name: note

# S3 配置
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# WeDav 配置
web_dav_url: https://dav.jianguoyun.com/dav/
web_dav_dir: note/
web_dav_username: xxxxxxx@qq.com
web_dav_password: xxxxxxxxxxxxxxxx
# 如果部署在二级目录，需求填写这个，否则 Swagger 错误，不使用无需关注
# base_path: /obcsapi

# wechat 测试号/公众号
wechat_token: xxxxxxxxxxxxxx # 微信公众平台的Token
wechat_appid: xxxxxxxxxxxxxx # 微信公众平台的AppID
wechat_secret: xxxxxxxxxxxxxx # 微信公众平台的AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID 关注测试号后获取的
wechat_template_id: xxxxxxxxxxxxxx # 微信模板消息 ID 需要有 {{content.DATA}}

# 任务提醒
cron: "1/60 * * * * ?" # 每分钟检查一次 

# 权限设置 
# 允许 general all 接口修改全文件，并对外提供服务
allow_general_all_post: false
# 允许 general all 接口获取全文件，并对外提供服务
allow_general_all_get: false
# 允许 ![[]] 替换获取全文件，并对前端登录用户提供服务
allow_wiki_link_all: false


### Token Settings 自定义路径使用的 Token ，不知道路径可打开 debug 
/ob/general: token/token2.json