name: obcsapi-go
version: v4.1.0
description: by kkbt
host: 0.0.0.0
port: 8900
token_path: ./token/
token1_live_time: 72h

# å‰ç«¯ååœ°å€ é‚®ä»¶ä¸­ç™»å½•é“¾æ¥ä¼šç”¨åˆ°
front_url: https://kkbt.gitee.io/obweb/#/Memos
backend_url: api.ftls.xyz
wechat_return_str: "ğŸ“© å·²ä¿å­˜ï¼Œ<a href='https://note.ftls.xyz/#/ZK/202209050658'>ç‚¹å‡»æŸ¥çœ‹ä»Šæ—¥ç¬”è®°</a>"

# Obsidian æ–‡ä»¶å¤¹è®¾ç½®

ob_daily_dir: æ—¥å¿—/
ob_daily_attachment_dir: æ—¥å¿—/é™„ä»¶/
ob_daily_other_dir: æ”¯æŒç±»æ–‡ä»¶/
# å›¾åºŠæ–‡ä»¶ æœ‰å››éƒ¨åˆ†æ„æˆ url æ–‡ä»¶å¤¹åŠå‰ç¼€ï¼ŒåŸåå­—ï¼Œéšæœºå­—ç¬¦
# å›¾åºŠæ–‡ä»¶å¤¹åŠæ–‡ä»¶å‰ç¼€ eg 2006-01-02 15:04:05 å¦‚ æŒ‰æœˆå­˜æ”¾æ˜¯ 01/ ; æŒ‰ å¹´å­˜æ”¾ 2006/ ; æ–‡ä»¶å‰ç¼€ 200601 ; æ–‡ä»¶å¤¹å’Œæ–‡ä»¶å‰ç¼€ 200601/200601_
images_hosted_url: http://localhost:8900/images/
images_hosted_fmt: 200601/kkbt_
images_hosted_use_raw_name: true # å›¾åºŠæ–‡ä»¶æ˜¯å¦ä½¿ç”¨åŸåå­— true or false
images_hosted_random_name_length: 5 # å›¾åºŠæ–‡ä»¶éšæœºå­—ç¬¦å‘½å éšæœºå­—ç¬¦é•¿åº¦
# ç™¾åº¦ OCR https://ai.baidu.com/ai-doc/OCR/zk3h7xz52 è¯¥é¡¹ç½®ç©ºæˆ–åˆ é™¤æ­¤é¡¹åˆ™ä¸è¿›è¡Œ OCR æ³¨æ„è¯¥é¡¹æœ‰æ•ˆæœŸ 30 å¤©
# https://ai.baidu.com/ai-doc/REFERENCE/Ck3dwjhhu
# bd_ocr_access_token: xxxxx.xxxxx.xxxxx.xxxxx.xxxxx-xxxxx

# S3 -> 1 ; CouchDb -> 2 ; Local -> 3
data_source: 3

# CouchDb é…ç½®
couchdb_url: http://admin:password@localhost:5984/
couchdb_db_name: note

# S3 é…ç½®
access_key: xxxxxxxxxxxxxx
secret_key: xxxxxxxxxxxxxx
end_point: https://cos.ap-beijing.myqcloud.com
region: ap-beijing
bucket: obsidion-xxxxxxxxxxxxxx

# LocalStorage (RemotelySave WebDav) http://localhost:8900/webdav ç”¨æˆ·è‡ªå®šä¹‰è´¦æˆ·å¯†ç 
webdav_server: true
webdav_username: kkbt
webdav_password: kkbt123
webdav_dir: testdb/

# wechat æµ‹è¯•å·/å…¬ä¼—å·
wechat_token: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„Token
wechat_appid: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„AppID
wechat_secret: xxxxxxxxxxxxxx # å¾®ä¿¡å…¬ä¼—å¹³å°çš„AppSecret
wechat_openid: xxxxxxxxxxxxxx # OpenID
wechat_template_id: xxxxxxxxxxxxxx # å¾®ä¿¡æ¨¡æ¿æ¶ˆæ¯ ID éœ€è¦æœ‰ {{content.DATA}}

# ä»»åŠ¡æé†’
email_reminder_time: 0700 # æŒ‡æ¯å¤© 07:00 

# smtp é‚®ç®±æœåŠ¡
smtp_mail:
  smtp_host: smtpdm.aliyun.com
  port: 80
  username: no-reply@mail.ftls.xyz
  password: xxxxxxxxxxxxxx
  # ä»¥ä¸‹ä¸€ä¸ªæ˜¯å‘é€è€… ä¸€ä¸ªæ˜¯æ¥å—è€…
  mail_sender_address: no-reply@mail.ftls.xyz
  mail_sender_name: "ObCSAPI"
  mail_send_to: yourmail@foxmail.com